// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeBerA7iYGmC2BDmzVRWXWH_g8zP5c6b8',
    appId: '1:372499435617:web:ed81217cadcea3423d1a20',
    messagingSenderId: '372499435617',
    projectId: 'telemed-map-proj',
    authDomain: 'telemed-map-proj.firebaseapp.com',
    storageBucket: 'telemed-map-proj.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFXy6Va3VVGnIxv33wFg_kWagfjzttXNs',
    appId: '1:372499435617:android:237f0774697feab53d1a20',
    messagingSenderId: '372499435617',
    projectId: 'telemed-map-proj',
    storageBucket: 'telemed-map-proj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRf4TR-3rBg5cFT2qclUBbVvfr1FCbnwI',
    appId: '1:372499435617:ios:884a6a0a71b155f33d1a20',
    messagingSenderId: '372499435617',
    projectId: 'telemed-map-proj',
    storageBucket: 'telemed-map-proj.firebasestorage.app',
    iosBundleId: 'com.example.telemediceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRf4TR-3rBg5cFT2qclUBbVvfr1FCbnwI',
    appId: '1:372499435617:ios:884a6a0a71b155f33d1a20',
    messagingSenderId: '372499435617',
    projectId: 'telemed-map-proj',
    storageBucket: 'telemed-map-proj.firebasestorage.app',
    iosBundleId: 'com.example.telemediceProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeBerA7iYGmC2BDmzVRWXWH_g8zP5c6b8',
    appId: '1:372499435617:web:7bf373851ab0ec493d1a20',
    messagingSenderId: '372499435617',
    projectId: 'telemed-map-proj',
    authDomain: 'telemed-map-proj.firebaseapp.com',
    storageBucket: 'telemed-map-proj.firebasestorage.app',
  );

}